sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.haxelib-local/

language: scala

addons:
  apt:
    packages:
    - libgc1c2

before_install:
  - mkdir $HOME/untar
  - mkdir $HOME/opt
  - travis_retry wget --output-document=$HOME/neko.tar.gz http://nekovm.org/media/neko-2.0.0-linux64.tar.gz
  - tar zxvf $HOME/neko.tar.gz -C $HOME/untar/
  - mv $HOME/untar/neko-*/ $HOME/opt/neko/
  - travis_retry wget --output-document=$HOME/haxe.tar.gz http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux64/"$HAXE_FILE"
  - tar zxvf $HOME/haxe.tar.gz -C $HOME/untar/
  - mv $HOME/untar/haxe-*/ $HOME/opt/haxe/
  - export PATH=$PATH:$HOME/opt/haxe:$HOME/opt/neko
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/opt/neko
  - export HAXE_STD_PATH=$HOME/opt/haxe/std
  - haxelib setup $HOME/.haxelib-local
  - travis_retry haxelib install hxjava --always

install:
  - sbt ";haxelibInstallDependencies;+update"

script:
  - sbt +test

before_cache:
  - find $HOME/.sbt -name '*.lock' | xargs rm
  - find $HOME/.ivy2 -name 'ivydata-*.properties' | xargs rm

jdk:
  - oraclejdk8

env:
  matrix:
    # Haxe 3.2.1
    - HAXE_FILE=haxe_2015-10-12_master_deab442.tar.gz

before_deploy:
  - travis_retry git clone --depth=1 $secret_git ./secret

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    condition: -e ./deploy.sh && "$HAXE_FILE" == "haxe_2015-10-12_master_deab442.tar.gz"
    all_branches: true
